import { StyleSheet } from "react-native";

export const hamkkuStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FBF9F5",
  },
  header: {
    height: 56,
    paddingHorizontal: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F0FFE5",
  },
  coinWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  coinCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8F48E",
    borderWidth: 1,
    borderColor: "#9CCCA0",
  },
  coinIcon: {
    fontFamily: "Galmuri9",
    fontSize: 12,
    color: "#7EC985",
  },
  coinText: {
    fontFamily: "Galmuri9",
    fontSize: 12,
    color: "#464B47",
  },
  preview: {
    height: 304,
    position: "relative",
    overflow: "hidden",
  },
  previewWall: {
    height: 202,
    alignItems: "center",
    paddingTop: 30,
  },
  speechBubble: {
    width: 204,
    height: 94,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: "#9CCCA0",
    backgroundColor: "#FAFFF9",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0px 2px 4px rgba(104, 171, 110, 0.25)",
  },
  speechText: {
    fontFamily: "Galmuri9",
    fontSize: 15,
    lineHeight: 22,
    color: "#2D322E",
    textAlign: "center",
  },
  speechTail: {
    position: "absolute",
    bottom: -8,
    width: 16,
    height: 16,
    backgroundColor: "#FAFFF9",
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#9CCCA0",
    transform: [{ rotate: "45deg" }],
  },
  nameButton: {
    marginTop: 18,
    paddingHorizontal: 6,
    height: 18,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  nameText: {
    fontFamily: "Galmuri9",
    fontSize: 12,
    color: "#E67972",
  },
  floorLine: {
    height: 3,
    backgroundColor: "#464B47",
  },
  previewFloor: {
    height: 99,
    alignItems: "center",
  },
  hamsterWrap: {
    position: "absolute",
    top: 168,
    left: "50%",
    width: 124,
    height: 124,
    marginLeft: -62,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  hamsterImage: {
    width: 124,
    height: 124,
    resizeMode: "contain",
  },
  accessoryLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 4,
  },
  accessoryText: {
    fontFamily: "GalmuriBold",
    fontSize: 24,
    color: "#2D322E",
  },
  doneButtonWrap: {
    position: "absolute",
    right: 16,
    bottom: 16,
  },
  tabs: {
    height: 72,
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 34,
    paddingTop: 16,
    gap: 20,
    borderTopWidth: 1,
    borderColor: "#DCE1DD",
  },
  tabButton: {
    minWidth: 48,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  activeTabButton: {
    backgroundColor: "#F0FFE5",
  },
  tabText: {
    fontFamily: "Galmuri9",
    fontSize: 14,
    color: "#919692",
  },
  activeTabText: {
    color: "#2D322E",
  },
  itemList: {
    paddingHorizontal: 29,
    paddingBottom: 120,
  },
  itemGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    columnGap: 4,
    rowGap: 10,
  },
  itemWrap: {
    width: 106,
    marginBottom: 10,
  },
  itemCard: {
    width: 106,
    height: 106,
    borderRadius: 7,
    borderWidth: 0.5,
    borderColor: "#9CCCA0",
    backgroundColor: "#FAFFF9",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  selectedCard: {
    borderColor: "#9CCCA0",
    borderWidth: 0.5,
  },
  colorItemCard: {
    justifyContent: "flex-start",
  },
  checkIcon: {
    position: "absolute",
    top: -1,
    left: -1,
    width: 30,
    height: 30,
    zIndex: 2,
  },
  itemPreviewCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0FFE5",
    overflow: "hidden",
  },
  itemHamster: {
    width: 60,
    height: 60,
    resizeMode: "contain",
  },
  colorPreview: {
    width: "100%",
    height: "100%",
  },
  ownedBadge: {
    position: "absolute",
    right: 4,
    bottom: 4,
    minWidth: 48,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E0F9BF",
  },
  ownedText: {
    fontFamily: "Galmuri9",
    fontSize: 11,
    color: "#7EC985",
  },
  priceBadge: {
    position: "absolute",
    right: 4,
    bottom: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  smallCoin: {
    width: 15,
    height: 15,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8F48E",
    borderWidth: 1,
    borderColor: "#9CCCA0",
  },
  smallCoinText: {
    fontFamily: "Galmuri9",
    fontSize: 9,
    color: "#7EC985",
  },
  priceText: {
    fontFamily: "Galmuri9",
    fontSize: 11,
    color: "#7EC985",
  },
  itemName: {
    marginTop: 6,
    fontFamily: "Galmuri9",
    fontSize: 12,
    lineHeight: 18,
    color: "#3D2B27",
  },
  purchaseButtonWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 28,
    alignItems: "center",
  },
  purchaseButton: {
    width: 132,
    height: 48,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#E67972",
    backgroundColor: "#FFDBEB",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "inset 4px 4px 2px rgba(255,255,255,0.45), inset -3px -3px 3px rgba(230,121,114,0.28)",
  },
  purchaseText: {
    fontFamily: "GalmuriBold",
    fontSize: 18,
    color: "#7A5751",
  },
  applyPanel: {
    marginTop: 52,
    paddingHorizontal: 44,
    alignItems: "center",
  },
  applyBubble: {
    width: "100%",
    height: 104,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#FFDBEB",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  applyBubbleText: {
    fontFamily: "Galmuri9",
    fontSize: 16,
    color: "#2D322E",
  },
  applyActions: {
    marginTop: 16,
    flexDirection: "row",
    gap: 12,
  },
  outlineAction: {
    width: 132,
    height: 48,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  greenAction: {
    width: 132,
    height: 48,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    backgroundColor: "#F0FFE5",
    alignItems: "center",
    justifyContent: "center",
  },
  actionText: {
    fontFamily: "Galmuri9",
    fontSize: 14,
    color: "#7A5751",
  },
  nameSheetBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.30)",
    zIndex: 20,
  },
  nameSheet: {
    height: 266,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: "#FBFBF5",
    paddingHorizontal: 30,
    paddingTop: 12,
  },
  handle: {
    alignSelf: "center",
    width: 112,
    height: 3,
    borderRadius: 2,
    backgroundColor: "#AAAFAB",
    marginBottom: 20,
  },
  sheetTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sheetText: {
    fontFamily: "Galmuri9",
    fontSize: 15,
    color: "#464B47",
  },
  sheetDoneText: {
    fontFamily: "Galmuri9",
    fontSize: 15,
    color: "#7EC985",
  },
  nicknameInputWrap: {
    marginTop: 50,
    borderBottomWidth: 2,
    borderBottomColor: "#9CCCA0",
    paddingBottom: 8,
  },
  nicknameInput: {
    fontFamily: "Galmuri9",
    fontSize: 16,
    color: "#2D322E",
    textAlign: "center",
  },
  counter: {
    position: "absolute",
    right: 0,
    bottom: 10,
    fontFamily: "Galmuri9",
    fontSize: 12,
    color: "#919692",
  },
});
