import { StyleSheet } from "react-native";

export const attendanceStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FBFBF5",
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    height: 52,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  monthRow: {
    width: 335,
    alignSelf: "center",
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  arrowButton: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  monthButton: {
    width: 179,
    height: 35,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    backgroundColor: "#F0FFE5",
    alignItems: "center",
    justifyContent: "center",
  },
  monthText: {
    color: "#7A5751",
    fontFamily: "WantedSansSemiBold",
    fontSize: 16,
    lineHeight: 24,
  },
  weekRow: {
    marginTop: 25,
    width: 335,
    alignSelf: "center",
    flexDirection: "row",
  },
  weekText: {
    width: `${100 / 7}%`,
    color: "#5F6460",
    fontFamily: "Galmuri9",
    fontSize: 12,
    textAlign: "center",
  },
  calendar: {
    marginTop: 24,
    width: 335,
    height: 240,
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "flex-start",
    rowGap: 6,
  },
  dayCell: {
    width: `${100 / 7}%`,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCircle: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: "#DCE1DD",
    alignItems: "center",
    justifyContent: "center",
  },
  todayCircle: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: "#FFDBEB",
    alignItems: "center",
    justifyContent: "center",
  },
  dayText: {
    color: "#919692",
    fontFamily: "WantedSansRegular",
    fontSize: 13,
  },
  todayText: {
    color: "#7A5751",
  },
  futureText: {
    color: "#7A5751",
  },
  attendanceLabel: {
    position: "absolute",
    top: -18,
    zIndex: 2,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    borderRadius: 2,
    backgroundColor: "#F0FFE5",
  },
  attendanceLabelText: {
    color: "#E67972",
    fontFamily: "Galmuri9",
    fontSize: 10,
  },
  dailyPoint: {
    marginTop: 19,
    marginRight: 2,
    textAlign: "right",
    color: "#7A5751",
    fontFamily: "Galmuri9",
    fontSize: 11,
  },
  summaryRow: {
    height: 89,
    marginTop: 11,
    flexDirection: "row",
    gap: 6,
  },
  monthCountCard: {
    width: 111,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    borderRadius: 5,
    backgroundColor: "#FAFFF9",
    padding: 10,
  },
  streakCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    borderRadius: 5,
    backgroundColor: "#FAFFF9",
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  cardTitle: {
    color: "#5F6460",
    fontFamily: "Galmuri9",
    fontSize: 10,
  },
  monthCount: {
    marginTop: "auto",
    textAlign: "right",
    color: "#7A5751",
    fontFamily: "WantedSansRegular",
    fontSize: 14,
  },
  rewardRow: {
    marginTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rewardItem: {
    width: 40,
    alignItems: "center",
    gap: 1,
  },
  rewardPoint: {
    color: "#919692",
    fontFamily: "WantedSansRegular",
    fontSize: 10,
  },
  rewardPointActive: {
    color: "#E67972",
  },
  rewardCircle: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    borderWidth: 1,
    borderColor: "#9CCCA0",
    backgroundColor: "#F0FFE5",
    alignItems: "center",
    justifyContent: "center",
  },
  rewardDay: {
    color: "#7EC985",
    fontFamily: "WantedSansRegular",
    fontSize: 10,
  },
  streakResetNote: {
    width: 335,
    alignSelf: "center",
    marginTop: 10,
    color: "#787D79",
    fontFamily: "WantedSansRegular",
    fontSize: 12,
    lineHeight: 18,
  },
  actionRow: {
    marginTop: 23,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  hiddenActionRow: {
    display: "none",
  },
  pixelButton: {
    width: 69,
    height: 48,
    borderRadius: 4,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#5F6460",
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 1,
    elevation: 3,
  },
  rewardButton: {
    borderColor: "#ECA9BF",
    backgroundColor: "#FFD9EB",
  },
  checkButton: {
    borderColor: "#9CCCA0",
    backgroundColor: "#E8F9C7",
  },
  disabledButton: {
    borderColor: "#C8CDCA",
    backgroundColor: "#E6EAE8",
  },
  pixelButtonText: {
    color: "#7A5751",
    fontFamily: "GalmuriBold",
    fontSize: 15,
  },
  disabledButtonText: {
    color: "#AAAFAB",
  },
  rewardToast: {
    position: "absolute",
    left: -4,
    bottom: 42,
    width: 86,
    height: 62,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    backgroundColor: "#5F6460",
    justifyContent: "center",
    paddingLeft: 14,
  },
  rewardToastTitle: {
    color: "#FFFFFF",
    fontFamily: "Galmuri9",
    fontSize: 12,
  },
  rewardToastText: {
    marginTop: 5,
    color: "#B8EA83",
    fontFamily: "Galmuri9",
    fontSize: 10,
  },
});
